#
# Copyright 2016, Data61, CSIRO
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(NICTA_GPL)
#

apps-$(CONFIG_APP_VM_OPTIPLEX9020_ONEVM_CROSS_VM_DATAPORTS)    += optiplex9020_onevm_cross_vm_dataport

optiplex9020_onevm_cross_vm_dataport-y     = common libsel4 libmuslc libsel4vka libsel4allocman libsel4muslcsys \
libsel4vspace libsel4utils libpci libcpio libsel4vmm libelf libutils libsel4camkes libsel4sync libsel4debug libsel4muslccamkes libsel4simple libsel4simple-stable libsel4platsupport libethdrivers liblwip

optiplex9020_onevm_cross_vm_dataport: $(optiplex9020_onevm_cross_vm_dataport-y)
