#!/bin/sh

#
# Copyright 2016, Data 61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(D61_GPL)
#

# Script for testing cross vm dataport support

READ=dataport_read
WRITE=dataport_write

DP1_NAME=/dev/dp1
DP2_NAME=/dev/dp2

MESSAGE1="Hello, World!"
MESSAGE2="abcdefghijklmnopqrstuvwxyz"

LARGE_FILE=/opt/text/lipsum

echo "Writing to $DP1_NAME: '$MESSAGE1'"
echo $MESSAGE1 | $WRITE $DP1_NAME
echo "Reading from $DP1_NAME: '`$READ $DP1_NAME`'"

echo "Writing to $DP2_NAME: '$MESSAGE2'"
echo $MESSAGE2 | $WRITE $DP2_NAME
echo "Reading from dataport: '`$READ $DP2_NAME`'"

echo "Filling $DP2_NAME..."
cat $LARGE_FILE | $WRITE $DP2_NAME
