/*
 * Copyright 2017, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#include <assert.h>
#include <camkes/error.h>
#include <stdio.h>
#include <stdint.h>
#include <sel4/sel4.h>

/*- set config_irqs = configuration[me.name].get("vm_irqs") -*/
/*- set config_pci = configuration[me.name].get("pci_devices") -*/
/*- set ioapic_irqs = [] -*/
/*- set msi_irqs = [] -*/
/*- set irq_to_bdf = {} -*/

/*- set irqnotification_object = alloc_obj('irq_notification_obj', seL4_NotificationObject) -*/
/*- set irqnotification_object_cap = alloc_cap('irq_notification_obj', irqnotification_object, read=True) -*/

/*# Map irq -> PCI bdf #*/
/*- for device in config_pci -*/
    /*- do irq_to_bdf.update({device['irq']:(device['bus'], device['dev'], device['fun'])}) -*/
/*- endfor -*/

/*- if config_irqs is not none -*/
    /*- for irq in config_irqs -*/
        /*- if 'ioapic' in irq -*/
            /*- set cap = alloc('irq_ioapic%d_%d' % (irq['ioapic'], irq['source']), seL4_IRQHandler, vector=irq['dest'], ioapic = irq['ioapic'], ioapic_pin = irq['source'], level = irq['level_trig'], polarity = irq['active_low'], notification=my_cnode[irqnotification_object_cap]) -*/
            /*- do ioapic_irqs.append( (irq['name'].strip('"'), irq['ioapic'], irq['source'], irq['level_trig'], irq['active_low'], irq['dest'], cap) ) -*/
        /*- else -*/
            /*# assume that an irq is msi if it's not generated by an ioapic pin #*/
            /*- set bus, dev, fun = irq_to_bdf[irq['name']] -*/
            /*- set cap = alloc('msi_%s' % (irq['name']), seL4_IRQHandler, vector=irq['source'], pci_bus=bus, pci_dev=dev, pci_fun=fun, handle=irq['handle'], notification=my_cnode[irqnotification_object_cap]) -*/
            /*- do msi_irqs.append( (irq['name'].strip('"'), irq['pci_irq_line'], irq['source'], cap) ) -*/
        /*- endif -*/
    /*- endfor -*/
/*- endif -*/

int irqs_ioapic_num_irqs() {
    return /*? len(ioapic_irqs) ?*/;
}

const char * irqs_ioapic_get_irq(int i, seL4_CPtr *irq_handler, uint8_t *ioapic, uint8_t *source, int *level_trig, int *active_low, uint8_t *dest) {
    /*- if len(ioapic_irqs) == 0 -*/
        return NULL;
    /*- else -*/
        switch (i) {
            /*- for name, ioapic, source, level_trig, active_low, dest, cap in ioapic_irqs -*/
                case /*? loop.index0 ?*/:
                    *irq_handler = /*? cap ?*/;
                    *ioapic = /*? ioapic ?*/;
                    *source = /*? source ?*/;
                    *level_trig = /*? level_trig ?*/;
                    *active_low = /*? active_low ?*/;
                    *dest = /*? dest ?*/;
                    return "/*? name ?*/";
            /*- endfor -*/
        default:
            return NULL;
        }
    /*- endif -*/
}

int irqs_msi_num_irqs() {
    return /*? len(msi_irqs) ?*/;
}

const char * irqs_msi_get_irq(int i, seL4_CPtr *irq_handler, uint8_t *irq, uint8_t *source) {
    /*- if len(msi_irqs) == 0 -*/
        return NULL;
    /*- else -*/
        switch (i) {
            /*- for name, irq, source, cap in msi_irqs -*/
                case /*? loop.index0 ?*/:
                    *irq_handler = /*? cap ?*/;
                    *irq = /*? irq ?*/;
                    *source = /*? source ?*/;
                    return "/*? name ?*/";
            /*- endfor -*/
        default:
            return NULL;
        }
    /*- endif -*/
}
