#!/bin/sh
#
# Copyright 2016, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(D61_BSD)
#

# Script for testing cross vm dataport support

INIT=dataport_init
READ=dataport_read
WRITE=dataport_write

DP1_NAME=dp1
DP1_SIZE=0x1000

DP2_NAME=dp2
DP2_SIZE=0x10000

MESSAGE1="Hello, World!"
MESSAGE2="abcdefghijklmnopqrstuvwxyz"

LARGE_FILE=/opt/text/lipsum

$INIT $DP1_NAME $DP1_SIZE $DP2_NAME $DP2_SIZE

echo "Writing to $DP1_NAME: '$MESSAGE1'"
echo $MESSAGE1 | $WRITE /dev/$DP1_NAME
echo "Reading from $DP1_NAME: '`$READ /dev/$DP1_NAME`'"

echo "Writing to $DP2_NAME: '$MESSAGE2'"
echo $MESSAGE2 | $WRITE /dev/$DP2_NAME
echo "Reading from dataport: '`$READ /dev/$DP2_NAME`'"

echo "Filling $DP2_NAME..."
cat $LARGE_FILE | $WRITE /dev/$DP2_NAME
