#
# Copyright 2016, Data 61
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(D61_GPL)
#

TARGET = libcamkes.a
include ../../common.mk

OBJS = dataport.o emits_event.o consumes_event.o

include ../../common_lib.mk
