#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(DATA61_GPL)
#

apps-$(CONFIG_APP_VM_CMA34CR_VCHAN)    += cma34cr_vchan

cma34cr_vchan-y     = common libsel4 libmuslc libsel4vka libsel4allocman libsel4muslcsys \
libsel4vspace libsel4utils libpci libcpio libsel4vmm libelf libutils libsel4camkes libsel4sync libsel4debug libsel4muslccamkes libsel4simple libsel4simple-default libsel4platsupport libethdrivers liblwip

cma34cr_vchan: $(cma34cr_vchan-y)
