#!/bin/sh

#
# Copyright 2016, Data 61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(D61_GPL)
#

#
# Template for custom init script for guest linux
# that loads some additional kernel modules.
#
# __LINUX_VERSION__ is used as a placeholder for the linux version
# number triple (e.g. "4.7.2").

# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

insmod /lib/modules/__LINUX_VERSION__/kernel/drivers/vmm/dataport.ko
insmod /lib/modules/__LINUX_VERSION__/kernel/drivers/vmm/consumes_event.ko
insmod /lib/modules/__LINUX_VERSION__/kernel/drivers/vmm/emits_event.ko

# Initialising the Vchan driver
insmod /lib/modules/__LINUX_VERSION__/kernel/drivers/vmm/vmm_manager.ko
if [ "$?" -lt "0" ]; then
	echo "vmm driver initialisation FAILED with $?" > /dev/kmsg
# else
	# echo "Starting tests" 2>&1 > /dev/kmsg
	# /bin/vmm_manager_tests > /dev/kmsg
	# if [ "$?" -eq "0" ]; then
		# echo "vmm driver tests concluded with no errors" > /dev/kmsg
	# fi
	# var=`/bin/vm_guest_manip num`
	# if [ "$var" -eq "0" ]; then
		# /bin/sel4_vchan_testsuite > /dev/kmsg
	# else
		# echo "$var skipping tests.." > /dev/kmsg
	# fi
fi

# VFAT FS kernel module synthesised from Cogent
insmod /lib/modules/__LINUX_VERSION__/kernel/drivers/vfat/cg-fat.ko
insmod /lib/modules/__LINUX_VERSION__/kernel/drivers/vfat/cg-vfat.ko

exec /sbin/init $*
